# Generated by Django 3.0.5 on 2020-08-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='post',
        ),
    ]
