# Generated by Django 3.0.5 on 2020-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0002_auto_20200808_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
