# Generated by Django 3.0.5 on 2020-08-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0006_auto_20200809_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
